const sections = [
 ['1. Responsable','Nemy OCR es una aplicación desarrollada por Nemy Studios. Para consultas de privacidad, escribe a nemystudios@gmail.com.'],
 ['2. Información que procesa','Nemy OCR puede procesar fotografías tomadas por el usuario, imágenes seleccionadas voluntariamente, texto reconocido, historial local y archivos PDF o Word creados por solicitud del usuario. No examina automáticamente la galería completa.'],
 ['3. Reconocimiento de texto','Nemy OCR utiliza componentes de Google ML Kit para detectar documentos y reconocer texto. Nemy Studios no mantiene servidores propios para recibir ni almacenar copias de las imágenes o documentos escaneados.'],
 ['4. Historial y almacenamiento local','Los escaneos guardados permanecen en el dispositivo y pueden eliminarse desde la aplicación. Al desinstalarla, estos datos normalmente se eliminan, salvo archivos exportados fuera de la app.'],
 ['5. Publicidad y consentimiento','Nemy OCR utiliza Google AdMob. Google y sus socios pueden tratar identificadores del dispositivo, datos técnicos e interacciones con anuncios según sus políticas y el consentimiento aplicable.'],
 ['6. Permisos','Cámara para fotografiar documentos; selector de imágenes para elegir archivos; e Internet para publicidad, consentimiento y servicios relacionados.'],
 ['7. Información no solicitada directamente','Nemy OCR no requiere una cuenta y Nemy Studios no solicita contraseñas, datos bancarios, ubicación GPS precisa, audio del micrófono ni datos biométricos.'],
 ['8. Compartir y exportar','El usuario elige la aplicación o servicio de destino mediante Android al compartir texto o exportar archivos.'],
 ['9. Menores de edad','Nemy OCR es una herramienta general de productividad y no está diseñada específicamente para niños.'],
 ['10. Cambios y contacto','Esta política podrá actualizarse cuando cambien funciones o proveedores. Contacto: nemystudios@gmail.com.'],
]
export default function OcrPrivacy(){return <main className="container-nemy py-20 md:py-28"><article className="card p-7 md:p-14"><span className="inline-flex rounded-full border border-blue-400/20 bg-blue-400/10 px-3 py-2 text-xs font-extrabold uppercase tracking-widest text-blue-200">Documento oficial</span><h1 className="mt-5 text-5xl font-black tracking-tight md:text-7xl">Política de privacidad de Nemy OCR</h1><p className="mt-4 text-nemy-muted"><strong>Última actualización:</strong> 20 de julio de 2026</p><div className="mt-10 space-y-9">{sections.map(([h,p])=><section key={h}><h2 className="text-2xl font-black">{h}</h2><p className="mt-3 leading-relaxed text-slate-300">{p}</p></section>)}</div><p className="mt-10 text-slate-300">Política de Google: <a className="text-cyan-300 underline" href="https://policies.google.com/privacy" target="_blank" rel="noreferrer">policies.google.com/privacy</a></p></article></main>}
